server:
  port: 8081
dubbo:
  application:
    name: product-service-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 28001


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qv-v7?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root